FROM golang:alpine

#ADD microblog-server /go/src/github.com/ComputePractice2017/microblog-server
ADD microblog-server /go/src/github.com/practice/microblog-server

#RUN go get "github.com/gorilla/handlers"
#RUN go get "gopkg.in/gorethink/gorethink.v3"

RUN go install github.com/practice/microblog-server

ENTRYPOINT /go/bin/microblog-server

ENV RETHINKDB_HOST db

EXPOSE 8000